<?php
/**
 * @file
 * Contains core functions for the SexyBookmarks module.
 */

// Shareaholic API key.
define('SB_APIKEY', '19afe428dd0d6406b366252cf4204ec6e');

/**
 * Include additional files.
 */
foreach (module_list() as $module) {
  if (file_exists($file = dirname(__FILE__) . "/includes/{$module}.inc")) {
    require_once $file;
  }
}

/**
 * Implements hook_init().
 */
function sexybookmarks_init() {
  drupal_add_js('SHRSB_Settings = {};', 'inline');
}

/**
 * Implements hook_flush_caches().
 */
function sexybookmarks_flush_caches() {
  file_unmanaged_delete_recursive('public://sexybookmarks');
  return array();
}

/**
 * Implements hook_theme().
 */
function sexybookmarks_theme($existing, $type, $theme, $path) {
  return array(
    'sexybookmarks' => array(
      'variables' => array(
        'url' => NULL,
        'title' => NULL,
        'text' => NULL,
        'profile' => NULL,
        'config' => NULL,
      ),
    ),
    'sexybookmarks_services' => array(
      'render element' => 'form_element',
      'file' => 'sexybookmarks_profiles.inc',
      'path' => drupal_get_path('module', 'sexybookmarks') . '/plugins/export_ui'
    ),
  );
}

/**
 * Theme callback for SexyBookmarks.
 */
function theme_sexybookmarks($variables) {
  if (($config = sexybookmarks_get_config($variables))) {
    $id = "{$variables['profile']}-" . rand(1000, 9999);
    $directory = md5($config['service']);
    $api = 'http://www.shareaholic.com/api/sprite/?v=2&apikey=' . SB_APIKEY . '&service=' . urlencode($config['service']);
    $settings = drupal_json_encode(array(
      "sexybookmarks-{$id}" => array_merge(
        $config,
        array(
          'apikey' => SB_APIKEY,
          'src' => file_create_url("public://sexybookmarks/{$directory}"),
          'link' => isset($variables['url']) ? $variables['url'] : '',
          'title' => isset($variables['title']) ? $variables['title'] : (
            drupal_get_title() ? strip_tags(drupal_get_title()) : check_plain(variable_get('site_name', 'Drupal'))
          ),
          'notes' => isset($variables['text']) ? $variables['text'] : '',
          'localize' => TRUE,
        )
      )
    ));
    drupal_add_js("jQuery.extend(SHRSB_Settings, {$settings});", 'inline');
    drupal_add_js(sexybookmarks_get_file('http://www.shareaholic.com/media/js/jquery.shareaholic-publishers-sb.min.js'));
    drupal_add_css(sexybookmarks_get_file($api, "{$directory}/sprite.css"), array('basename' => "{$directory}.css"));
    drupal_add_css("
      .sexybookmarks-{$id} ul.shr-socials li.shareaholic {
        background-image: url('" . file_create_url(sexybookmarks_get_file("{$api}&apitype=png", "{$directory}/sprite.png")) . "') !important;
      }
    ", 'inline');
    return "<div class='sexybookmarks-{$id}'></div>";
  }
  return '';
}

/**
 * Prepare configuration for SexyBookmarks theme callback.
 */
function sexybookmarks_get_config(&$variables) {
  $config = NULL;

  if (isset($variables['profile'])) {
    ctools_include('export');
    if (($profile = ctools_export_crud_load('sexybookmarks_profiles', $variables['profile']))) {
      if (empty($profile->disabled)) {
        $config = $profile->config;
        if (isset($variables['config'])) {
          $config = array_merge($config, $variables['config']);
        }
      }
      else {
        watchdog('sexybookmarks', 'Provided profile disabled (!profile).', array('!profile' => $variables['profile']), WATCHDOG_ERROR);
      }
    }
    else {
      watchdog('sexybookmarks', 'Invalid profile provided (!profile).', array('!profile' => $variables['profile']), WATCHDOG_ERROR);
    }
  }

  elseif (isset($variables['config'])) {
    $config = $variables['config'];
  }

  else {
    watchdog('sexybookmarks', 'No profile or configuration provided.', array(), WATCHDOG_ERROR);
  }

  // Allow other modules to alter configuration.
  drupal_alter('sexybookmarks_config', $config, $variables);

  return $config;
}

/**
 *
 */
function sexybookmarks_get_file($url, $destination = NULL) {
  $md5 = md5($url);
  $pathinfo = pathinfo($url);
  $destination = isset($destination) ? $destination : $pathinfo['basename'];
  $file = "public://sexybookmarks/{$destination}";

  if (!file_exists($file)) {
    $request = drupal_http_request($url);
    $pathinfo = pathinfo($file);
    if ($request->code == 200) {
      if (file_prepare_directory($dir = $pathinfo['dirname'], FILE_CREATE_DIRECTORY)) {
        file_unmanaged_save_data($request->data, $file);
      }
    }

    else {
      return $url;
    }
  }
  return $file;
}
