<?php
/**
 * @file
 * Contains core functions for the SexyBookmarks module.
 */

// Shareaholic API key.
define('SB_APIKEY', '19afe428dd0d6406b366252cf4204ec6e');

/**
 * Include additional files.
 */
foreach (module_list() as $module) {
  if (file_exists($file = dirname(__FILE__) . "/includes/{$module}.inc")) {
    require_once $file;
  }
}

/**
 * Implements hook_theme().
 */
function sexybookmarks_theme($existing, $type, $theme, $path) {
  return array(
    'sexybookmarks' => array(
      'variables' => array(
        'url' => NULL,
        'title' => NULL,
        'text' => NULL,
        'profile' => NULL,
        'config' => NULL,
      ),
    ),
    'sexybookmarks_services' => array(
      'render element' => 'form_element',
      'file' => 'sexybookmarks_profiles.inc',
      'path' => drupal_get_path('module', 'sexybookmarks') . '/plugins/export_ui'
    ),
  );
}

/**
 * Theme callback for SexyBookmarks.
 */
function theme_sexybookmarks($variables) {
  if (($config = sexybookmarks_get_config($variables))) {
    $settings = drupal_json_encode(array(
      "sexybookmarks-{$variables['profile']}" => array_merge(
        $config,
        array(
          'apikey' => SB_APIKEY,
          'link' => isset($variables['url']) ? $variables['url'] : '',
          'title' => isset($variables['title']) ? $variables['title'] : '',
          'notes' => isset($variables['text']) ? $variables['text'] : '',
        )
      )
    ));
    drupal_add_js("SHRSB_Settings = {$settings};", 'inline');
    drupal_add_js('http://www.shareaholic.com/media/js/jquery.shareaholic-publishers-sb.min.js', 'external');
    //drupal_add_js(drupal_get_path('module', 'sexybookmarks') . '/jquery.shareaholic-publishers-sb.js');

    return "<div class='sexybookmarks-{$variables['profile']}'></div>";
  }
  return '';
}

/**
 * Prepare configuration for SexyBookmarks theme callback.
 */
function sexybookmarks_get_config(&$variables) {
  $config = NULL;

  if (isset($variables['profile'])) {
    ctools_include('export');
    if (($profile = ctools_export_crud_load('sexybookmarks_profiles', $variables['profile']))) {
      if (empty($profile->disabled)) {
        $config = $profile->config;
        if (isset($variables['config'])) {
          $config = array_merge($config, $variables['config']);
        }
      }
      else {
        watchdog('sexybookmarks', 'Provided profile disabled (!profile).', array('!profile' => $variables['profile']), WATCHDOG_ERROR);
      }
    }
    else {
      watchdog('sexybookmarks', 'Invalid profile provided (!profile).', array('!profile' => $variables['profile']), WATCHDOG_ERROR);
    }
  }

  elseif (isset($variables['config'])) {
    $config = $variables['config'];
  }

  else {
    watchdog('sexybookmarks', 'No profile or configuration provided.', array(), WATCHDOG_ERROR);
  }

  // Allow other modules to alter configuration.
  drupal_alter('sexybookmarks_config', $config, $variables);

  return $config;
}
